# Welcome to Jekyll!
name: Get Off Pocket
title: Get Off Pocket
description: >-
  A guide to alternatives for Pocket
url: "https://getoffpocket.com"
baseurl: ""

gtag_id: G-YRF0EZ9WWS

digital_ocean_referral_url: https://m.do.co/c/c0f96d3af928
donate_url: https://donate.stripe.com/00wbJ12pPa3M0Rtcso0Ba0a

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap # keep this last

# Collections configuration
# This tells Jekyll to treat the folders _open_source and _proprietary as
# collections of pages to be rendered.
collections:
  posts:
    output: true
    permalink: /blog/:title/
  open_source:
    output: true
    permalink: /open-source/:name/
  proprietary:
    output: true
    permalink: /proprietary/:name/
  get_started:
    output: true
    permalink: /get-started/:path/

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - scripts
  - private
