# Site settings
title: Get Off Pocket - Read-It-Later Alternatives
description: A guide to Pocket (read-it-later) alternatives
url: https://getoffpocket.com
baseurl: ""

# Google Analytics
google_analytics: G-YRF0EZ9WWS

# Build settings
markdown: kramdown

# Collections configuration
collections:
  open_source:
    output: true
    permalink: /open-source/:name
  proprietary:
    output: true
    permalink: /proprietary/:name
