# Welcome to Jekyll!
title: Get Off Pocket
description: >-
  A guide to alternatives for Pocket, which is shutting down.
url: "https://getoffpocket.com"
baseurl: ""

gtag_id: G-YRF0EZ9WWS

# Collections configuration
# This tells Jekyll to treat the folders _open_source and _proprietary as
# collections of pages to be rendered.
collections:
  open_source:
    output: true
    permalink: /open-source/:name/
  proprietary:
    output: true
    permalink: /proprietary/:name/
